blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PostListView.as_view(), name='board_index'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/write', views.post_write, name="post_write"),
    path('post/update/<int:pk>', views.post_update, name="post_update"),
    path('post/<int:post_pk>/comment/write', views.comment_write, name='comment_write'),
    path('post/delete/<int:pk>', views.post_delete, name='post_delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>', views.comment_delete, name='comment_delete'),
    path('search/', views.SearchFormView.as_view(), name='search'),
]

fourthproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='index'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
          name='password_change'),
    path('accounts/password_change/done/',
          auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
          name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/',
          auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
          name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/',
          auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
          name='password_reset_complete'),
    path('user/', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('posts/', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('model/', views.ModelsPageView.as_view(), name='model'),
    path('model/post/', views.CreateModelsView.as_view(), name='model_post'),
    path('model/detail/<int:model_id>/', views.detail, name="model_detail"),
    path('model/detail/<int:model_id>/delete', views.delete, name="delete"),
    path('model/<int:model_id>/edit/', views.edit, name="edit"),

    path('model/filter/cute/', views.filter_cute, name="filter_cute"),
    path('model/filter/cool/', views.filter_cool, name="filter_cool"),
    path('model/filter/bnw/', views.filter_bnw, name="filter_bnw"),
    path('model/filter/plus/', views.filter_plus, name="filter_plus"),

    path('photo/', views.PhotoPageView.as_view(), name="photo"),
    path('photo/post/', views.PhotoCreatePostView.as_view(), name="photo_post"),
    path('photo/detail/<int:photo_id>/', views.photo_detail, name="photo_detail"),
    path('photo/detail/<int:photo_id>/delete', views.photo_delete, name="photo_delete"),
    path('photo/<int:photo_id>/edit/', views.photo_edit, name="photo_edit"),


    path('photo/filter/cute/', views.photo_filter_cute, name="photo_filter_cute"),
    path('photo/filter/cool/', views.photo_filter_cool, name="photo_filter_cool"),
    path('photo/filter/bnw/', views.photo_filter_bnw, name="photo_filter_bnw"),
    path('photo/filter/plus/', views.photo_filter_plus, name="photo_filter_plus"),

]

blog/models.py
from django.db import models
from django.urls import reverse_lazy
from user.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    writer = models.CharField(max_length=100)
    post_date = models.DateTimeField(auto_now_add=True)
    post_title = models.CharField(max_length=100)
    post_contents = RichTextUploadingField()
    post_hit = models.PositiveIntegerField(default=0)



    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse_lazy('post_detail', args=[str(self.id)])

    def get_previous_post(self):
        return self.get_previous_by_post_date()

    def get_next_post(self):
        return self.get_next_by_post_date()

    @property
    def update_counter(self):
        self.post_hit = self.post_hit + 1
        self.save()

    @property
    def is_auth(self, nick):
        if writer != nick:
            return False
        else:
            return True


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, related_name='comments')
    comment_writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_contents = models.CharField(max_length=200)

    class Meta:
        ordering = ['-id']

posts/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from user.models import User


class Models(models.Model):
    title = models.CharField(max_length=20)
    text = models.TextField(default='', null=True, blank=True)
    image1 = models.ImageField(upload_to = 'images/')
    image2 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    image3 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    image4 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    image5 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    thumbnail = ImageSpecField(source='image1', processors=[ResizeToFill(120,80)], format='JPEG')


    CATEGORY_CHOICES = (
        ('큐티', '큐티'),
        ('청량', '청량'),
        ('흑백사진', '흑백사진'),
        ('플러스모델', '플러스모델'),
    )

    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES, null=True)

    def __str__(self):
        return self.title


class Photo(models.Model):
    title = models.CharField(max_length=20)
    text = models.TextField(default='', null=True, blank=True)
    image1 = models.ImageField(upload_to = 'images/')
    image2 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    image3 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    image4 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    image5 = models.ImageField(upload_to = 'images/', default='', null=True, blank=True)
    thumbnail = ImageSpecField(source='image1', processors=[ResizeToFill(120,80)], format='JPEG')

    CATEGORY_CHOICES = (
        ('큐티', '큐티'),
        ('청량', '청량'),
        ('흑백사진', '흑백사진'),
        ('플러스모델', '플러스모델'),
    )

    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES, null=True)

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from .models import Models, Photo


class ModelsForm(forms.ModelForm):

    class Meta :
        model = Models
        fields = ['title', 'text', 'image1', 'image2', 'image3', 'image4', 'image5', 'category']


class PhotoForm(forms.ModelForm):

    class Meta :
        model = Photo
        fields = ['title', 'text', 'image1', 'image2', 'image3', 'image4', 'image5', 'category']

posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView  # new
from django.urls import reverse_lazy  # new
from django.contrib.auth.decorators import login_required
from .forms import ModelsForm, PhotoForm
from .models import Models, Photo


from django.core.paginator import Paginator


class ModelsPageView(ListView):
    model = Models
    template_name = 'model/model.html'
    paginate_by = 4
    queryset = Models.objects.all()

    def get_queryset(self, *args, **kwargs):
        if self.kwargs:
            return Models.objects.filter(category=self.kwargs['category']).order_by('-id')
        else:
            query = Models.objects.all().order_by('-id')
            return query


class CreateModelsView(CreateView):
    model = Models
    form_class = ModelsForm
    template_name = 'model/model_post.html'
    success_url = reverse_lazy('model')


def detail(request, model_id):
    post_detail = Models.objects.get(pk=model_id)
    return render(request, 'model/model_detail.html', {'post_detail': post_detail})


def delete(request, model_id):
    delete_model = Models.objects.get(id=model_id)
    delete_model.delete()
    return redirect('model')


def edit(request, model_id):
    model = Models.objects.get(id=model_id)

    if request.method == "POST":
        form = ModelsForm(request.POST, request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
            model.title = form.cleaned_data['title']
            model.text = form.cleaned_data['text']
            model.image1 = form.cleaned_data['image1']
            model.image2 = form.cleaned_data['image2']
            model.image3 = form.cleaned_data['image3']
            model.image4 = form.cleaned_data['image4']
            model.image5 = form.cleaned_data['image5']
            model.save()
            return redirect('model_detail', model_id)

    else:
        form = ModelsForm()
    return render(request, 'model/model_edit.html', {'form': form, })


def filter_cute(request):
    post_cute = Models.objects.filter(category="큐티")
    cute_paginator = Paginator(post_cute, 4)
    cute_page = request.GET.get('page')
    cute_posts = cute_paginator.get_page(cute_page)
    return render(request, 'model/filter_cute.html', {'post_cute': post_cute,
                                                      'cute_posts': cute_posts,
                                                      'cute_paginator': cute_paginator, })


def filter_cool(request):
    post_cool = Models.objects.filter(category="청량")
    cool_paginator = Paginator(post_cool, 4)
    cool_page = request.GET.get('page')
    cool_posts = cool_paginator.get_page(cool_page)
    return render(request, 'model/filter_cool.html', {'post_cool': post_cool,
                                                      'cool_posts': cool_posts,
                                                      'cool_paginator': cool_paginator, })


def filter_bnw(request):
    post_bnw = Models.objects.filter(category="흑백사진")
    bnw_paginator = Paginator(post_bnw, 4)
    bnw_page = request.GET.get('page')
    bnw_posts = bnw_paginator.get_page(bnw_page)
    return render(request, 'model/filter_bnw.html', {'post_bnw': post_bnw,
                                                     'bnw_posts': bnw_posts,
                                                     'bnw_paginator': bnw_paginator, })


def filter_plus(request):
    post_plus = Models.objects.filter(category="플러스모델")
    plus_paginator = Paginator(post_plus, 4)
    plus_page = request.GET.get('page')
    plus_posts = plus_paginator.get_page(plus_page)
    return render(request, 'model/filter_plus.html', {'post_plus': post_plus,
                                                      'plus_posts': plus_posts,
                                                      'plus_paginator': plus_paginator, })


#####################################################


class PhotoPageView(ListView):
    model = Photo
    template_name = 'photo/photo.html'
    paginate_by = 4
    queryset = Photo.objects.all()

    def get_queryset(self, *args, **kwargs):
        if self.kwargs:
            return Photo.objects.filter(category=self.kwargs['category']).order_by('-id')
        else:
            query = Photo.objects.all().order_by('-id')
            return query


class PhotoCreatePostView(CreateView):
    model = Photo
    form_class = PhotoForm
    template_name = 'photo/photo_post.html'
    success_url = reverse_lazy('photo')


def photo_detail(request, photo_id):
    photo_post_detail = Photo.objects.get(pk=photo_id)
    return render(request, 'photo/photo_detail.html', {'photo_post_detail': photo_post_detail})


def photo_delete(request, photo_id):
    delete_photo = Photo.objects.get(id=photo_id)
    delete_photo.delete()
    return redirect('photo')


def photo_edit(request, photo_id):
    photo = Photo.objects.get(id=photo_id)

    if request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
            photo.title = form.cleaned_data['title']
            photo.text = form.cleaned_data['text']
            photo.image1 = form.cleaned_data['image1']
            photo.image2 = form.cleaned_data['image2']
            photo.image3 = form.cleaned_data['image3']
            photo.image4 = form.cleaned_data['image4']
            photo.image5 = form.cleaned_data['image5']
            photo.save()
            return redirect('photo_detail', photo_id)

    else:
        form = PhotoForm()
    return render(request, 'photo/photo_edit.html', {'form': form, })


def photo_filter_cute(request):
    photo_post_cute = Photo.objects.filter(category="큐티")
    photo_cute_paginator = Paginator(photo_post_cute, 4)
    photo_cute_page = request.GET.get('page')
    photo_cute_posts = photo_cute_paginator.get_page(photo_cute_page)

    return render(request, 'photo/photo_filter_cute.html', {'photo_post_cute': photo_post_cute,
                                                            'photo_cute_posts': photo_cute_posts,
                                                            'photo_cute_paginator': photo_cute_paginator, })


def photo_filter_cool(request):
    photo_post_cool = Photo.objects.filter(category="청량")
    photo_cool_paginator = Paginator(photo_post_cool, 4)
    photo_cool_page = request.GET.get('page')
    photo_cool_posts = photo_cool_paginator.get_page(photo_cool_page)

    return render(request, 'photo/photo_filter_cool.html', {'photo_post_cool': photo_post_cool,
                                                            'photo_cool_posts': photo_cool_posts,
                                                            'photo_cool_paginator': photo_cool_paginator, })


def photo_filter_bnw(request):
    photo_post_bnw = Photo.objects.filter(category="흑백사진")
    photo_bnw_paginator = Paginator(photo_post_bnw, 4)
    photo_bnw_page = request.GET.get('page')
    photo_bnw_posts = photo_bnw_paginator.get_page(photo_bnw_page)

    return render(request, 'photo/photo_filter_bnw.html', {'photo_post_bnw': photo_post_bnw,
                                                           'photo_bnw_posts': photo_bnw_posts,
                                                           'photo_bnw_paginator': photo_bnw_paginator, })


def photo_filter_plus(request):
    photo_post_plus = Photo.objects.filter(category="플러스모델")
    photo_plus_paginator = Paginator(photo_post_plus, 4)
    photo_plus_page = request.GET.get('page')
    photo_plus_posts = photo_plus_paginator.get_page(photo_plus_page)

    return render(request, 'photo/photo_filter_plus.html', {'photo_post_plus': photo_post_plus,
                                                            'photo_plus_posts': photo_plus_posts,
                                                            'photo_plus_paginator': photo_plus_paginator, })

posts/templates/model/filter_bnw.html
<!-- temlaptes/home.html -->

{% extends 'model/model_base.html' %}
{% block content %}

        <div class="b">
            <div class="array">
                {% for bnw in bnw_posts %}
                        <div class="card">
                            <div class="box-1">
                                <a href="{% url 'model_detail' bnw.id %}">
                                    <img src="{{ bnw.image1.url }}" width="200" height="250">
                                </a>
                            </div>
                            <div class="box-2">
                                <p class="c">{{ bnw.title }}</p>
                                <p class="d">{{ user.username }}</p>
                            </div>
                        </div>
                {% endfor %}
        </div>
        </div>

  <div class="paginator">
     {% if bnw_posts.has_previous %}
      <a href="?page={{ bnw_posts.previous_page_number }}">◀</a>
    {% else %}
      <span>◀</span>
  {% endif %}
    {% if bnw_posts.has_next %}
      <a href="?page={{ bnw_posts.next_page_number }}">▶</a>
    {% else %}
      <span>▶</span>
    {% endif %}
  </div>


{% endblock content %}

posts/templates/model/filter_cool.html
{% extends 'model/model_base.html' %}
{% block content %}


        <div class="b">
            <div class="array">
                {% for cool in cool_posts %}
                        <div class="card">
                            <div class="box-1">
                                <a href="{% url 'model_detail' cool.id %}">
                                    <img src="{{ cool.image1.url }}" width="200" height="250">
                                </a>
                            </div>
                            <div class="box-2">
                                <p class="c">{{ cool.title }}</p>
                                <p class="d">{{ user.username }}</p>
                            </div>
                        </div>
                {% endfor %}
            </div>
        </div>

  <div class="paginator">
    {% if cool_posts.has_previous %}
      <a href="?page={{ cool_posts.previous_page_number }}">◀</a>
    {% else %}
      <span>◀</span>
  {% endif %}
    {% if cool_posts.has_next %}
      <a href="?page={{ cool_posts.next_page_number }}">▶</a>
    {% else %}
      <span>▶</span>
    {% endif %}
  </div>


{% endblock content %}

posts/templates/model/filter_cute.html
{% extends 'model/model_base.html' %}
{% block content %}

    <div class="b">
        <div class="array">
                {% for cute in cute_posts %}
                        <div class="card">
                            <div class="box-1">
                                <a href="{% url 'model_detail' cute.id %}">
                                    <img src="{{ cute.image1.url }}" width="200" height="250">
                                </a>
                            </div>
                            <div class="box-2">
                                <p class="c">{{ cute.title }}</p>
                                <p class="d">{{ user.username }}</p>
                            </div>
                        </div>
                {% endfor %}
            </div>
    </div>

<div class="paginator">
    {% if cute_posts.has_previous %}
      <a href="?page={{ cute_posts.previous_page_number }}">◀</a>
    {% else %}
      <span>◀</span>
  {% endif %}
    {% if cute_posts.has_next %}
      <a href="?page={{ cute_posts.next_page_number }}">▶</a>
    {% else %}
      <span>▶</span>
    {% endif %}
</div>


{% endblock content %}

posts/templates/model/filter_plus.html
{% extends 'model/model_base.html' %}
{% block content %}


       <div class="b">
         <div class="array">
                {% for plus in plus_posts %}
                        <div class="card">
                            <div class="box-1">
                                <a href="{% url 'model_detail' plus.id %}">
                                    <img src="{{ plus.image1.url }}" width="200" height="250">
                                </a>
                            </div>
                            <div class="box-2">
                                <p class="c">{{ plus.title }}</p>
                                <p class="d">{{ user.username }}</p>
                            </div>
                        </div>
                {% endfor %}
            </div>
       </div>

    <div class="paginator">
        {% if plus_posts.has_previous %}
          <a href="?page={{ plus_posts.previous_page_number }}">◀</a>
        {% else %}
          <span>◀</span>
        {% endif %}
        {% if plus_posts.has_next %}
          <a href="?page={{ plus_posts.next_page_number }}">▶</a>
        {% else %}
          <span>▶</span>
        {% endif %}
    </div>
{% endblock content %}

posts/templates/model/model.html
{% extends 'model/model_base.html' %}
{% block content %}
    <div class="b">
        <div class="array">
            {% for post in models_list %}
                <div class="card">
                       <div class="box-1">
                           <a href="{% url 'model_detail' post.id %}">
                               <img src="{{ post.image1.url }}" width="350" height="350" alt = "{{ post.title }}">
                           </a>
                       </div>
                        <div class="box-2">
                            <p class="c">{{ post.title }}</p>
                            <p class="d">{{ user.username }}</p>
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

posts/templates/model/model_base.html
<head>
    {% load  staticfiles %}
    <link rel="stylesheet" href="{% static 'css/model_photo.css' %}">
</head>
<body>

    <a href="{% url 'index' %}">
        <img class="logo" src="{% static 'image/logo.png' %}" alt="logo">
    </a>
    <div class="title">
        <a href="{% url 'model' %}">model</a>
    </div>
    <div class="category">
        {% if user.is_authenticated %}
            <a id="user_name" href="{% url 'profile' user.pk %}">{{ user.username }}</a>
            <a href="{% url 'logout' %}">logout</a>
        {% else %}
            <a href="{% url 'login' %}">login</a>
            <a href="{% url 'signup' %}">registration</a>
        {% endif %}
    </div>
    <div class="a">
        <div class="keywords">
            <div class="inline">
                <a class="keywords_title" href="">keywords</a>
            </div>
            <div class="inline">
                <a href="{% url 'filter_cute' %}"><button class="cute">큐티</button></a>
                <a href="{% url 'filter_cool' %}"><button class="cool">청량</button></a>
                <a href="{% url 'filter_bnw' %}"><button class="mono">흑백</button></a>
                <a href="{% url 'filter_plus' %}"><button class="plus">플러스모델</button></a>
            </div>
            <div class="inline">
                {% if user.role == '모델' %}
                    <a href="{% url 'model_post' %}"><button class="upload_post">upload</button></a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="paginator">
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">◀</a>
            {% else %}
            <span>◀</span>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">▶</a>
            {% else %}
                <span>▶</span>
            {% endif %}
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</body>

posts/templates/model/model_detail.html
<head>
    {% load  staticfiles %}
    <link rel="stylesheet" href="{% static 'css/model_photo.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">


</head>
<body>
    <a href="{% url 'index' %}">
        <img class="logo" src="{% static 'image/logo.png' %}" alt="logo">
    </a>
    <div class="title">
        <a href="{% url 'model' %}">model</a>
    </div>
    <div class="category">
        {% if user.is_authenticated %}
            <a id="user_name" href="{% url 'profile' user.pk %}">{{ user.username }}</a>
            <a href="{% url 'logout' %}">logout</a>
        {% else %}
            <a href="{% url 'login' %}">login</a>
            <a href="{% url 'signup' %}">registration</a>
        {% endif %}
    </div>
    <div class="f">
        <div class="detail">
            <p class="detail_title">{{ post_detail.title }}</p>
            <p class="detail_username">{{ user.username }}</p>
            {% if post_detail.image1 != '' %}
                <img src="{{ post_detail.image1.url }}" width = "220" alt = "{{ post_detail.title }}">
            {% endif %}
            {% if post_detail.image2 != '' %}
                <img src="{{ post_detail.image2.url }}" width = "220" alt = "{{ post_detail.title }}">
            {% endif %}
            {% if post_detail.image3 != '' %}
                <img src="{{ post_detail.image3.url }}" width = "220" alt = "{{ post_detail.title }}">
            {% endif %}
            {% if post_detail.image4 != '' %}
                <img src="{{ post_detail.image4.url }}" width = "220" alt = "{{ post_detail.title }}">
            {% endif %}
            {% if post_detail.image5 != '' %}
                <img src="{{ post_detail.image5.url }}" width = "220" alt = "{{ post_detail.title }}">
            {% endif %}
            <p class="detail_content">{{ post_detail.text }}</p>
        </div>
    </div>
    <div class="g">
        <div class="detail_back">
            <a href="{% url 'model' %}"><button>back-model</button></a>
        </div>
        <div class="detail_active">
            {% if user.role == '모델' %}
                <a href="{% url 'edit' post_detail.id %}"><button>edit</button></a>
                <a href="{% url 'delete' post_detail.id %}"><button>delete</button></a>
            {% endif %}
        </div>
    </div>

</body>

posts/templates/model/model_edit.html
<head>
    {% load  staticfiles %}
    <link rel="stylesheet" href="{% static 'css/model_photo.css' %}">
</head>
<body>
    <a href="{% url 'index' %}">
        <img class="logo" src="{% static 'image/logo.png' %}" alt="logo">
    </a>
    <div class="title">
        <p>revise your photos!</p>
    </div>
    <div class="category">
        {% if user.is_authenticated %}
            <a id="user_name" href="{% url 'profile' user.pk %}">{{ user.username }}</a>
            <a href="{% url 'logout' %}">logout</a>
        {% else %}
            <a href="{% url 'login' %}">login</a>
            <a href="{% url 'signup' %}">registration</a>
        {% endif %}
    </div>
    <div class="container">
        <h1>수정 페이지</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <br>
            <button type="submit" class="sixth">submit</button>
        </form>
    </div>
</body>

posts/templates/model/model_post.html
<head>
    {% load  staticfiles %}
    <link rel="stylesheet" href="{% static 'css/model_photo.css' %}">
</head>
<body>
    <a href="{% url 'index' %}">
        <img class="logo" src="{% static 'image/logo.png' %}" alt="logo">
    </a>
    <div class="title">
        <p>upload your photos!</p>
    </div>
    <div class="category">
        {% if user.is_authenticated %}
            <a id="user_name" href="{% url 'profile' user.pk %}">{{ user.username }}</a>
            <a href="{% url 'logout' %}">logout</a>
        {% else %}
            <a href="{% url 'login' %}">login</a>
            <a href="{% url 'signup' %}">registration</a>
        {% endif %}
    </div>

    <div class="e">
        <div class="post">
            <form class="form-post" method="post" enctype="multipart/form-data">
                <div class="box-p1">
                    {% csrf_token %}
                </div>
                {{ form.as_p }}
            <button type="submit" class="post_button">upload</button>
        </form>
        </div>
    </div>
</body>